version: "3"
volumes:
  gatlinpush-data:
    driver: local
services:
  gatlinpush:
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - postgresdb:postgresdb
    volumes:
      - ./:/usr/src/app
    env_file: .env
  postgresdb:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - gatlinpush-data:/var/lib/postgres

    
  