from models import Installation, PushManager
from util.exceptions import InstallationException
from sqlalchemy.exc import IntegrityError

class InstallationRepo:

    @staticmethod
    def get(uuid):
        """
        Return one installation for a given
        uuid
        """

        installation = Installation.query.filter_by(
            uuid=uuid
        ).one_or_none()
        if installation is None:
            raise InstallationException("installation not exists", 404)
        return installation

    @staticmethod
    def get_by_deviceid(deviceid):
        """
        Return multiple installation for the given
        device_id
        """
        installation = Installation.query.filter_by(
            device_id=deviceid
        ).all()
        return installation

    @staticmethod
    def delete_by_deviceid(deviceid):
        """
        Delete all installations for the given
        device_id
        """
        installations = Installation.query.filter_by(
            device_id=deviceid
        ).all()
        if len(installations) > 0:
            for i in installations:
                i.delete()

    @staticmethod
    def delete(uuid):
        """
        Delete one particular installation
        """
        installation = Installation.query.filter_by(
            uuid=uuid
        ).one_or_none()
        if installation is None:
            raise InstallationException("Installation not exists", 404)
        installation.delete()

    @staticmethod
    def create(device_id, app_id):
        """
        app_id is the uuid
        device_id id generated by the android/ios device
        """
        pm = PushManager.query.filter_by(
            uuid=app_id
        ).one_or_none()
        if pm is None:
            raise InstallationException("App doesn't exist", 400)
        try:
            installation = Installation(pm.id, device_id)
            return installation.save()
        except IntegrityError as ie:
            raise InstallationException("This device is already registered with this app", 400)
