"""empty message

Revision ID: 4635d97427d3
Revises: a00c400a63a0
Create Date: 2017-06-16 20:50:09.427422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4635d97427d3'
down_revision = 'a00c400a63a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['push_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    # ### end Alembic commands ###
