"""empty message

Revision ID: 9a7d2df2ec4b
Revises: f4e82c1193f3
Create Date: 2017-06-24 10:58:23.979075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7d2df2ec4b'
down_revision = 'f4e82c1193f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push', sa.Column('sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push', 'sent')
    # ### end Alembic commands ###
