"""empty message

Revision ID: a00c400a63a0
Revises: b6aea89d2fb6
Create Date: 2017-06-12 21:37:42.835085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00c400a63a0'
down_revision = 'b6aea89d2fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_manager', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_manager', 'uuid')
    # ### end Alembic commands ###
