"""empty message

Revision ID: b6aea89d2fb6
Revises: 12f3b67a3c97
Create Date: 2017-06-10 12:38:45.359374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6aea89d2fb6'
down_revision = '12f3b67a3c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_manager', sa.Column('app_name', sa.String(length=100), nullable=True))
    op.add_column('push_manager', sa.Column('sns_arn', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_manager', 'sns_arn')
    op.drop_column('push_manager', 'app_name')
    # ### end Alembic commands ###
