"""empty message

Revision ID: f4e82c1193f3
Revises: 935a51929dab
Create Date: 2017-06-20 17:17:38.609129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e82c1193f3'
down_revision = '935a51929dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation', sa.Column('endpoint_arn', sa.String(length=512), nullable=True))
    op.create_unique_constraint('_one_install_ix', 'installation', ['app_id', 'device_id'])
    op.drop_constraint('_one_instal_ix', 'installation', type_='unique')
    op.add_column('push', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push', 'uuid')
    op.create_unique_constraint('_one_instal_ix', 'installation', ['app_id', 'device_id'])
    op.drop_constraint('_one_install_ix', 'installation', type_='unique')
    op.drop_column('installation', 'endpoint_arn')
    # ### end Alembic commands ###
